server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      api-key: <api-key>
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: deepseek-r1
      # log-requests: true
      # log-responses: true
  community:
    dashscope:
      chat-model:
        api-key: <api-key>
        model-name: qwen-max

# logging:
#   level:
#     root: debug
